//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSResponseParser_1_3_0Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WMSResponseParser_1_3_0Tests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;WMS_Capabilities version=&quot;1.3.0&quot; xmlns=&quot;http://www.opengis.net/wms&quot;
        ///  xmlns:xlink=&quot;http://www.w3.org/1999/xlink&quot;
        ///  xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///  xsi:schemaLocation=&quot;http://www.opengis.net/wms http://schemas.opengis.net/wms/1.3.0/capabilities_1_3_0.xsd&quot;&gt;
        ///&lt;!-- Service Metadata --&gt;
        ///&lt;Service&gt;
        ///  &lt;!-- The WMT-defined name for this type of service --&gt;
        ///  &lt;Name&gt;WMS&lt;/Name&gt;
        ///  &lt;!-- Human-readable title for pick lists --&gt;
        ///  &lt;Title&gt;Acme Corp. Map Server&lt;/T [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string example_capabilities_1_3_0 {
            get {
                return ResourceManager.GetString("example_capabilities_1_3_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;ServiceExceptionReport version=&quot;1.3.0&quot;
        ///  xmlns=&quot;http://www.opengis.net/ogc&quot;
        ///  xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///  xsi:schemaLocation=&quot;http://www.opengis.net/ogc http://schemas.opengis.net/wms/1.3.0/exceptions_1_3_0.xsd&quot;&gt;
        ///&lt;ServiceException&gt;
        ///Plain text message about an error.
        ///&lt;/ServiceException&gt;
        ///&lt;ServiceException code=&quot;InvalidUpdateSequence&quot;&gt;
        ///Another error message, this one with a service exception code supplied.
        ///&lt;/ServiceException&gt;
        ///&lt;ServiceException [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string example_exception_1_3_0 {
            get {
                return ResourceManager.GetString("example_exception_1_3_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&quot;ISO-8859-1&quot; standalone=&quot;no&quot; ?&gt;
        ///&lt;WMS_Capabilities version=&quot;1.3.0&quot;  xmlns=&quot;http://www.opengis.net/wms&quot;   xmlns:sld=&quot;http://www.opengis.net/sld&quot;   xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;   xmlns:ms=&quot;http://mapserver.gis.umn.edu/mapserver&quot;   xsi:schemaLocation=&quot;http://www.opengis.net/wms http://schemas.opengis.net/wms/1.3.0/capabilities_1_3_0.xsd  http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/sld_capabilities.xsd  http://mapserver.gis.umn.edu/mapserv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RGIS_MRCOG_GetCapabilities_1_3_0 {
            get {
                return ResourceManager.GetString("RGIS_MRCOG_GetCapabilities_1_3_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&quot;ISO-8859-1&quot; standalone=&quot;no&quot; ?&gt;
        ///&lt;WMS_Capabilities version=&quot;1.3.0&quot;  xmlns=&quot;http://www.opengis.net/wms&quot;   xmlns:sld=&quot;http://www.opengis.net/sld&quot;   xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;   xmlns:ms=&quot;http://mapserver.gis.umn.edu/mapserver&quot;   xsi:schemaLocation=&quot;http://www.opengis.net/wms http://schemas.opengis.net/wms/1.3.0/capabilities_1_3_0.xsd  http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/sld_capabilities.xsd  http://mapserver.gis.umn.edu/mapserv [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RGIS_NAIP_GetCapabilities_1_3_0 {
            get {
                return ResourceManager.GetString("RGIS_NAIP_GetCapabilities_1_3_0", resourceCulture);
            }
        }
    }
}
