//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArcGisMapServiceTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ArcGisMapServiceTests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;currentVersion&quot;: 10.1,
        ///    &quot;serviceDescription&quot;: &quot;Test Map Service Description&quot;,
        ///    &quot;mapName&quot;: &quot;Street Map Pro Data&quot;,
        ///    &quot;description&quot;: &quot;Street Map USA&quot;,
        ///    &quot;copyrightText&quot;: &quot;ESRI&quot;,
        ///    &quot;supportsDynamicLayers&quot;: false,
        ///    &quot;layers&quot;: [
        ///        {
        ///            &quot;id&quot;: 0,
        ///            &quot;name&quot;: &quot;Cities&quot;,
        ///            &quot;defaultVisibility&quot;: true,
        ///            &quot;parentLayerId&quot;: -1,
        ///            &quot;subLayerIds&quot;: null,
        ///            &quot;minScale&quot;: 0,
        ///            &quot;maxScale&quot;: 0
        ///        },
        ///        {
        ///           [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleESRICapabilitiesResponse {
            get {
                return ResourceManager.GetString("ExampleESRICapabilitiesResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {   &quot;currentVersion&quot;: 10.03,
        ///    &quot;serviceDescription&quot;: &quot;Atmospheric processes and phenomena. For example, resources describing cloud cover, weather, atmospheric conditions, climate change, and precipitation.&quot;,
        ///    &quot;mapName&quot;: &quot;Layers&quot;,
        ///    &quot;description&quot;: &quot;Atmospheric processes and phenomena. For example, resources describing cloud cover, weather, atmospheric conditions, climate change, and precipitation.&quot;,
        ///    &quot;copyrightText&quot;: &quot;INSIDE Idaho&quot;,
        ///    &quot;layers&quot;: [ { &quot;id&quot;: 0,
        ///                  &quot;name&quot;: &quot;Weathe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExampleInsideIdahoCapabilitiesResponse {
            get {
                return ResourceManager.GetString("ExampleInsideIdahoCapabilitiesResponse", resourceCulture);
            }
        }
    }
}
