//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsgsWaterDataTests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UsgsWaterDataTests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;sitesResponse xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.cuahsi.org/waterML/1.1/&quot;&gt;
        ///  &lt;queryInfo&gt;
        ///    &lt;creationTime&gt;2009-06-12T10:47:58.84375-07:00&lt;/creationTime&gt;
        ///    &lt;criteria MethodCalled=&quot;GetSiteInfo&quot;&gt;
        ///      &lt;parameter name=&quot;site&quot; value=&quot;LBR_TEST:USU-LBR-Mendon&quot; /&gt;
        ///      &lt;parameter name=&quot;site&quot; value=&quot;LBR_TEST:USU-LBR-Wellsville&quot; /&gt;
        ///    &lt;/criteria&gt;
        ///  &lt;/queryInfo&gt;
        ///  &lt;site&gt;
        ///    &lt;siteInfo&gt;
        ///      &lt;siteNa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetSiteInfoMultiple {
            get {
                return ResourceManager.GetString("GetSiteInfoMultiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;sitesResponse xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.cuahsi.org/waterML/1.1/&quot;&gt;
        ///  &lt;queryInfo&gt;
        ///    &lt;creationTime&gt;2009-06-12T10:47:58.84375-07:00&lt;/creationTime&gt;
        ///    &lt;criteria MethodCalled=&quot;GetSiteInfo&quot;&gt;
        ///      &lt;parameter name=&quot;site&quot; value=&quot;LBR_TEST:USU-LBR-Mendon&quot; /&gt;
        ///      &lt;parameter name=&quot;site&quot; value=&quot;LBR_TEST:USU-LBR-Wellsville&quot; /&gt;
        ///    &lt;/criteria&gt;
        ///  &lt;/queryInfo&gt;
        ///  &lt;site&gt;
        ///    &lt;siteInfo&gt;
        ///      &lt;siteNa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetSiteInfoMultiple_trimmed {
            get {
                return ResourceManager.GetString("GetSiteInfoMultiple_trimmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;sitesResponse xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.cuahsi.org/waterML/1.1/&quot;&gt;
        ///  &lt;queryInfo&gt;
        ///    &lt;creationTime&gt;2009-06-12T10:47:54.53125-07:00&lt;/creationTime&gt;
        ///    &lt;criteria MethodCalled=&quot;GetSites&quot; /&gt;
        ///    &lt;note&gt;ALL Sites(empty request)&lt;/note&gt;
        ///  &lt;/queryInfo&gt;
        ///  &lt;site&gt;
        ///    &lt;siteInfo&gt;
        ///      &lt;siteName&gt;Little Bear River at Mendon Road near Mendon, Utah&lt;/siteName&gt;
        ///      &lt;siteCode network=&quot;LBR&quot; siteID=&quot;1&quot;&gt;US [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetSites_All {
            get {
                return ResourceManager.GetString("GetSites_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;sitesResponse xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.cuahsi.org/waterML/1.1/&quot;&gt;
        ///  &lt;queryInfo&gt;
        ///    &lt;creationTime&gt;2009-06-12T10:47:54.53125-07:00&lt;/creationTime&gt;
        ///    &lt;criteria MethodCalled=&quot;GetSites&quot; /&gt;
        ///    &lt;note&gt;ALL Sites(empty request)&lt;/note&gt;
        ///  &lt;/queryInfo&gt;
        ///  &lt;site&gt;
        ///    &lt;siteInfo&gt;
        ///      &lt;siteName&gt;Little Bear River at Mendon Road near Mendon, Utah&lt;/siteName&gt;
        ///      &lt;siteCode network=&quot;LBR&quot; siteID=&quot;1&quot;&gt;US [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetSites_All_brief {
            get {
                return ResourceManager.GetString("GetSites_All_brief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;sitesResponse xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.cuahsi.org/waterML/1.1/&quot;&gt;
        ///  &lt;queryInfo&gt;
        ///    &lt;creationTime&gt;2009-06-12T10:47:57.5-07:00&lt;/creationTime&gt;
        ///    &lt;criteria MethodCalled=&quot;GetSiteInfo&quot;&gt;
        ///      &lt;parameter name=&quot;site&quot; value=&quot;LBR_TEST:USU-LBR-Wellsville&quot; /&gt;
        ///    &lt;/criteria&gt;
        ///  &lt;/queryInfo&gt;
        ///  &lt;site&gt;
        ///    &lt;siteInfo&gt;
        ///      &lt;siteName&gt;Little Bear River near Wellsville, Utah&lt;/siteName&gt;
        ///      &lt;siteCod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetSites_Mendon {
            get {
                return ResourceManager.GetString("GetSites_Mendon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;sitesResponse xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.cuahsi.org/waterML/1.1/&quot;&gt;
        ///  &lt;queryInfo&gt;
        ///    &lt;creationTime&gt;2009-06-12T10:47:57.5-07:00&lt;/creationTime&gt;
        ///    &lt;criteria MethodCalled=&quot;GetSiteInfo&quot;&gt;
        ///      &lt;parameter name=&quot;site&quot; value=&quot;LBR_TEST:USU-LBR-Wellsville&quot; /&gt;
        ///    &lt;/criteria&gt;
        ///  &lt;/queryInfo&gt;
        ///  &lt;site&gt;
        ///    &lt;siteInfo&gt;
        ///      &lt;siteName&gt;Little Bear River near Wellsville, Utah&lt;/siteName&gt;
        ///      &lt;siteCod [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetSites_Mendon_abbreviated {
            get {
                return ResourceManager.GetString("GetSites_Mendon_abbreviated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;sitesResponse xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.cuahsi.org/waterML/1.1/&quot;&gt;
        ///  &lt;queryInfo&gt;
        ///    &lt;creationTime&gt;2009-06-12T10:47:59.609375-07:00&lt;/creationTime&gt;
        ///    &lt;criteria MethodCalled=&quot;GetSitesByBox&quot;&gt;
        ///      &lt;parameter name=&quot;north&quot; value=&quot;90&quot; /&gt;
        ///      &lt;parameter name=&quot;south&quot; value=&quot;-90&quot; /&gt;
        ///      &lt;parameter name=&quot;east&quot; value=&quot;180&quot; /&gt;
        ///      &lt;parameter name=&quot;west&quot; value=&quot;-180&quot; /&gt;
        ///      &lt;parameter name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetSitesInBox {
            get {
                return ResourceManager.GetString("GetSitesInBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;sitesResponse xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.cuahsi.org/waterML/1.1/&quot;&gt;
        ///  &lt;queryInfo&gt;
        ///    &lt;creationTime&gt;2009-06-12T10:47:59.609375-07:00&lt;/creationTime&gt;
        ///    &lt;criteria MethodCalled=&quot;GetSitesByBox&quot;&gt;
        ///      &lt;parameter name=&quot;north&quot; value=&quot;90&quot; /&gt;
        ///      &lt;parameter name=&quot;south&quot; value=&quot;-90&quot; /&gt;
        ///      &lt;parameter name=&quot;east&quot; value=&quot;180&quot; /&gt;
        ///      &lt;parameter name=&quot;west&quot; value=&quot;-180&quot; /&gt;
        ///      &lt;parameter name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetSitesInBox_brief {
            get {
                return ResourceManager.GetString("GetSitesInBox_brief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;timeSeriesResponse xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.cuahsi.org/waterML/1.1/&quot;&gt;
        ///  &lt;queryInfo&gt;
        ///    &lt;creationTime&gt;2009-06-12T10:48:00.796875-07:00&lt;/creationTime&gt;
        ///    &lt;criteria MethodCalled=&quot;GetValues&quot;&gt;
        ///      &lt;parameter name=&quot;site&quot; value=&quot;LBR_TEST:USU-LBR-Mendon&quot; /&gt;
        ///      &lt;parameter name=&quot;variable&quot; value=&quot;LBR_TEST:USU3&quot; /&gt;
        ///      &lt;parameter name=&quot;startDate&quot; value=&quot;2005-08-05&quot; /&gt;
        ///      &lt;parameter name [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetValues_Mendon_usu3 {
            get {
                return ResourceManager.GetString("GetValues_Mendon_usu3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;timeSeriesResponse xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.cuahsi.org/waterML/1.1/&quot;&gt;
        ///  &lt;queryInfo&gt;
        ///    &lt;creationTime&gt;2009-06-12T10:48:02.78125-07:00&lt;/creationTime&gt;
        ///    &lt;criteria MethodCalled=&quot;GetValues&quot;&gt;
        ///      &lt;parameter name=&quot;site&quot; value=&quot;LBR_TEST:USU-LBR-Wellsville&quot; /&gt;
        ///      &lt;parameter name=&quot;variable&quot; value=&quot;LBR_TEST:USU41&quot; /&gt;
        ///      &lt;parameter name=&quot;startDate&quot; value=&quot;2007-10-04&quot; /&gt;
        ///      &lt;parameter  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetValues_MultiQC {
            get {
                return ResourceManager.GetString("GetValues_MultiQC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;timeSeriesResponse xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.cuahsi.org/waterML/1.1/&quot;&gt;
        ///  &lt;queryInfo&gt;
        ///    &lt;creationTime&gt;2009-06-12T10:48:04.609375-07:00&lt;/creationTime&gt;
        ///    &lt;criteria MethodCalled=&quot;GetValues&quot;&gt;
        ///      &lt;parameter name=&quot;site&quot; value=&quot;LBR_TEST:USU-LBR-Wellsville&quot; /&gt;
        ///      &lt;parameter name=&quot;variable&quot; value=&quot;LBR_TEST:USU41/QualityControlLevelID=2&quot; /&gt;
        ///      &lt;parameter name=&quot;startDate&quot; value=&quot;2007-10- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetValues_SingleQC {
            get {
                return ResourceManager.GetString("GetValues_SingleQC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;variablesResponse xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.cuahsi.org/waterML/1.1/&quot;&gt;
        ///  &lt;queryInfo&gt;
        ///    &lt;creationTime&gt;2009-06-12T10:47:52.078125-07:00&lt;/creationTime&gt;
        ///    &lt;criteria MethodCalled=&quot;GetVariableInfo&quot;&gt;
        ///      &lt;parameter name=&quot;variable&quot; /&gt;
        ///    &lt;/criteria&gt;
        ///    &lt;note&gt;OD Web Service&lt;/note&gt;
        ///  &lt;/queryInfo&gt;
        ///  &lt;variables&gt;
        ///    &lt;variable&gt;
        ///      &lt;variableCode vocabulary=&quot;LBR&quot; default=&quot;true&quot; variableID= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetVariableInfo_All {
            get {
                return ResourceManager.GetString("GetVariableInfo_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;variablesResponse xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.cuahsi.org/waterML/1.1/&quot;&gt;
        ///  &lt;queryInfo&gt;
        ///    &lt;creationTime&gt;2009-06-12T10:47:52.078125-07:00&lt;/creationTime&gt;
        ///    &lt;criteria MethodCalled=&quot;GetVariableInfo&quot;&gt;
        ///      &lt;parameter name=&quot;variable&quot; /&gt;
        ///    &lt;/criteria&gt;
        ///    &lt;note&gt;OD Web Service&lt;/note&gt;
        ///  &lt;/queryInfo&gt;
        ///  &lt;variables&gt;
        ///    &lt;variable&gt;
        ///      &lt;variableCode vocabulary=&quot;LBR&quot; default=&quot;true&quot; variableID= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetVariableInfo_All_brief {
            get {
                return ResourceManager.GetString("GetVariableInfo_All_brief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;timeSeriesResponse xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.cuahsi.org/waterML/1.1/&quot;&gt;
        ///  &lt;queryInfo&gt;
        ///    &lt;creationTime&gt;2009-06-12T10:48:06.75-07:00&lt;/creationTime&gt;
        ///    &lt;criteria MethodCalled=&quot;GetValuesForASite&quot;&gt;
        ///      &lt;parameter name=&quot;site&quot; value=&quot;LBR_TEST:USU-LBR-Mendon&quot; /&gt;
        ///      &lt;parameter name=&quot;startDate&quot; value=&quot;2005-08-05&quot; /&gt;
        ///      &lt;parameter name=&quot;endDate&quot; value=&quot;2005-08-06&quot; /&gt;
        ///    &lt;/criteria&gt;
        ///  &lt;/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetVaulesforSite_Mendon {
            get {
                return ResourceManager.GetString("GetVaulesforSite_Mendon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;timeSeriesResponse xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot; xmlns=&quot;http://www.cuahsi.org/waterML/1.1/&quot;&gt;
        ///  &lt;queryInfo&gt;
        ///    &lt;creationTime&gt;2009-06-12T10:48:35.453125-07:00&lt;/creationTime&gt;
        ///    &lt;criteria MethodCalled=&quot;GetValuesForASite&quot;&gt;
        ///      &lt;parameter name=&quot;site&quot; value=&quot;LBR_TEST:USU-LBR-Wellsville&quot; /&gt;
        ///      &lt;parameter name=&quot;startDate&quot; value=&quot;2007-10-04&quot; /&gt;
        ///      &lt;parameter name=&quot;endDate&quot; value=&quot;2007-12-31&quot; /&gt;
        ///    &lt;/criteri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetVaulesforSite_Wellsville {
            get {
                return ResourceManager.GetString("GetVaulesforSite_Wellsville", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #
        ///#
        ///# US Geological Survey
        ///# retrieved: 2012-09-20 01:49:40 EDT	(vaas01)
        ///#
        ///# The Site File stores location and general information about groundwater,
        ///# surface water, and meteorological sites
        ///# for sites in USA.
        ///#
        ///# File-format description:  http://waterdata.usgs.gov/nwis/?tab_delimited_format_info
        ///# Automated-retrieval info: http://waterservices.usgs.gov/Site-Service.html
        ///#
        ///# Contact:   gs-w_support_nwisweb@usgs.gov
        ///#
        ///# The following selected fields are included in this output:
        ///#
        ///#  agency_cd       -- Agen [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Site1031650_rdb {
            get {
                return ResourceManager.GetString("Site1031650_rdb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///&lt;!-- saved from url=(0079)http://waterservices.usgs.gov/nwis/site/?site=10316500&amp;seriesCatalogOutput=true --&gt;
        ///&lt;html&gt;&lt;head&gt;&lt;meta http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=UTF-8&quot;&gt;&lt;/head&gt;&lt;body class=&quot; hasGoogleVoiceExt&quot;&gt;&lt;pre style=&quot;word-wrap: break-word; white-space: pre-wrap;&quot;&gt;#
        ///#
        ///# US Geological Survey
        ///# retrieved: 2012-09-20 01:50:55 EDT	(vaas01)
        ///#
        ///# The Site File stores location and general information about groundwater,
        ///# surface water, and meteorological sites
        ///# for sites in USA.
        ///#
        ///# File-fo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Site1031650_SeriesCatalog_rdb {
            get {
                return ResourceManager.GetString("Site1031650_SeriesCatalog_rdb", resourceCulture);
            }
        }
    }
}
