//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WMSResponseParser_1_1_1Tests {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WMSResponseParser_1_1_1Tests.TestResources", typeof(TestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot; ?&gt;
        ///&lt;!-- The DTD (Document Type Definition) given here must correspond to the version number declared in the WMT_MS_Capabilities element below. --&gt;
        ///&lt;!DOCTYPE WMT_MS_Capabilities SYSTEM
        /// &quot;http://schemas.opengis.net/wms/1.1.1/WMS_MS_Capabilities.dtd&quot;
        /// [
        /// &lt;!-- Vendor-specific elements are defined here if needed. --&gt;
        /// &lt;!-- If not needed, just leave this EMPTY declaration.  Do not
        ///  delete the declaration entirely. --&gt;
        /// &lt;!ELEMENT VendorSpecificCapabilities EMPT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string example_capabilities_1_1_1 {
            get {
                return ResourceManager.GetString("example_capabilities_1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&quot;UTF-8&quot; standalone=&quot;no&quot; ?&gt;
        ///&lt;!DOCTYPE ServiceExceptionReport SYSTEM
        /// &quot;http://www.digitalearth.gov/wmt/xml/exception_1_1_1.dtd&quot;&gt;
        ///&lt;ServiceExceptionReport version=&quot;1.1.1&quot;&gt;
        ///  &lt;ServiceException&gt;
        ///    Plain text message about an error.
        ///  &lt;/ServiceException&gt;
        ///  &lt;ServiceException code=&quot;InvalidUpdateSequence&quot;&gt;
        ///    Another message, this one with a Service Exception code supplied.
        ///  &lt;/ServiceException&gt;
        ///  &lt;ServiceException&gt;
        ///    &lt;![CDATA[
        ///    Error in module &lt;foo.c&gt;, line 42
        ///
        ///    A message that [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string example_exception_1_1_1 {
            get {
                return ResourceManager.GetString("example_exception_1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&quot;ISO-8859-1&quot; standalone=&quot;no&quot; ?&gt;
        ///&lt;!DOCTYPE WMT_MS_Capabilities SYSTEM &quot;http://schemas.opengis.net/wms/1.1.1/WMS_MS_Capabilities.dtd&quot;
        /// [
        /// &lt;!ELEMENT VendorSpecificCapabilities EMPTY&gt;
        /// ]&gt;  &lt;!-- end of DOCTYPE declaration --&gt;
        ///
        ///&lt;WMT_MS_Capabilities version=&quot;1.1.1&quot;&gt;
        ///
        ///&lt;!-- MapServer version 5.6.6 OUTPUT=GIF OUTPUT=PNG OUTPUT=JPEG OUTPUT=WBMP OUTPUT=SWF OUTPUT=SVG SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=ICONV SUPPORTS=FRIBIDI SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RGIS_MRCOG_GetCapabilities_1_1_1 {
            get {
                return ResourceManager.GetString("RGIS_MRCOG_GetCapabilities_1_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&apos;1.0&apos; encoding=&quot;ISO-8859-1&quot; standalone=&quot;no&quot; ?&gt;
        ///&lt;!DOCTYPE WMT_MS_Capabilities SYSTEM &quot;http://schemas.opengis.net/wms/1.1.1/WMS_MS_Capabilities.dtd&quot;
        /// [
        /// &lt;!ELEMENT VendorSpecificCapabilities EMPTY&gt;
        /// ]&gt;  &lt;!-- end of DOCTYPE declaration --&gt;
        ///
        ///&lt;WMT_MS_Capabilities version=&quot;1.1.1&quot;&gt;
        ///
        ///&lt;!-- MapServer version 5.6.6 OUTPUT=GIF OUTPUT=PNG OUTPUT=JPEG OUTPUT=WBMP OUTPUT=SWF OUTPUT=SVG SUPPORTS=PROJ SUPPORTS=AGG SUPPORTS=FREETYPE SUPPORTS=ICONV SUPPORTS=FRIBIDI SUPPORTS=WMS_SERVER SUPPORTS=WMS_CLIENT SUPPORTS [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RGIS_NAIP_GetCapabilities_1_1_1 {
            get {
                return ResourceManager.GetString("RGIS_NAIP_GetCapabilities_1_1_1", resourceCulture);
            }
        }
    }
}
