{   "currentVersion": 10.03,
    "serviceDescription": "Atmospheric processes and phenomena. For example, resources describing cloud cover, weather, atmospheric conditions, climate change, and precipitation.",
    "mapName": "Layers",
    "description": "Atmospheric processes and phenomena. For example, resources describing cloud cover, weather, atmospheric conditions, climate change, and precipitation.",
    "copyrightText": "INSIDE Idaho",
    "layers": [ { "id": 0,
                  "name": "Weather Stations",
                  "parentLayerId": -1,
                  "defaultVisibility": false,
                  "subLayerIds": null,
                  "minScale": 0,
                  "maxScale": 0
                },
                { "id": 1,
                    "name": "Average Annual Precipitation",
                    "parentLayerId": -1,
                    "defaultVisibility": true,
                    "subLayerIds": null,
                    "minScale": 0,
                    "maxScale": 0
                },
                { "id": 2,
                    "name": "Agroclimate Zones",
                    "parentLayerId": -1,
                    "defaultVisibility": false,
                    "subLayerIds": null,
                    "minScale": 0,
                    "maxScale": 0
                },
                { "id": 3,
                    "name": "Koppen Climate Classification",
                    "parentLayerId": -1,
                    "defaultVisibility": false,
                    "subLayerIds": null,
                    "minScale": 0,
                    "maxScale": 0
                }],
    "tables": [],
    "spatialReference": { "wkid": 102100 },
    "singleFusedMapCache": false,
    "initialExtent": { "xmin": -13388407.0547671,
        "ymin": 5183377.78922474,
        "xmax": -12011528.1370593,
        "ymax": 6251737.10309281,
        "spatialReference": { "wkid": 102100 }
    },
    "fullExtent": { "xmin": -14581703.044678,
        "ymin": 2410401.05574306,
        "xmax": -6933274.01889905,
        "ymax": 6933084.98916851,
        "spatialReference": { "wkid": 102100 }
    },
    "units": "esriMeters",
    "supportedImageFormatTypes": "PNG24,PNG,JPG,DIB,TIFF,EMF,PS,PDF,GIF,SVG,SVGZ,AI,BMP",
    "documentInfo": { "Title": "Precipitation",
        "Author": "INSIDE Idaho",
        "Comments": "",
        "Subject": "",
        "Category": "",
        "Keywords": "",
        "Credits": ""
    },
    "capabilities": "Map,Query,Data"
}